name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: $0
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: storybook-static
        build_command: npm run build-storybook
